services:
  kepco:
    build:
      context: ./kepco
      dockerfile: Dockerfile
    image: ghcr.io/csnewcs/agent/kepco:latest
    container_name: kepco-api
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=4000
    volumes:
      - ./kepco/.env:/app/.env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile
    image: ghcr.io/csnewcs/agent/bot:latest
    container_name: discord-bot
    restart: unless-stopped
    network_mode: host
    privileged: true
    pid: host
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    depends_on:
      - kepco
    volumes:
      - ./bot/.env:/app/.env
      - /mnt/antigravity_workspaces:/mnt/antigravity_workspaces:ro
      - /home/fedora/git/TrackingTJNewSongs:/TrackingTJNewSongs:ro
      - /home/fedora/git/TrackingTJNewSongs:/home/fedora/git/TrackingTJNewSongs:ro
