package main

import (
	"bytes"
	"strings"
	"testing"
	"time"

	"github.com/bwmarrin/discordgo"
	qrcode "github.com/skip2/go-qrcode"
)

func TestGenerateQRCodeString(t *testing.T) {
	kst := time.FixedZone("KST", 9*3600)
	kstTime := time.Date(2026, 9, 4, 15, 20, 53, 0, kst)
	got := generateQRCodeString(kstTime)
	expected := "m20243683120260904152053"
	if got != expected {
		t.Fatalf("expected %s, got %s", expected, got)
	}

	// Test UTC time conversion to KST
	utcTime := time.Date(2026, 9, 4, 6, 20, 53, 0, time.UTC)
	gotUTC := generateQRCodeString(utcTime)
	if gotUTC != expected {
		t.Fatalf("expected %s, got %s", expected, gotUTC)
	}
}

func TestQRCodePNGEncoding(t *testing.T) {
	code := "m20243683120260904152053"
	pngBytes, err := qrcode.Encode(code, qrcode.Medium, 512)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if len(pngBytes) == 0 {
		t.Fatal("empty png bytes returned")
	}

	// Verify PNG magic header: 89 50 4E 47 0D 0A 1A 0A
	pngHeader := []byte{0x89, 'P', 'N', 'G', '\r', '\n', 0x1a, '\n'}
	if !bytes.HasPrefix(pngBytes, pngHeader) {
		t.Fatal("generated bytes do not start with PNG header")
	}
}

func TestQRComponentsStructure(t *testing.T) {
	builder := NewComponentsBuilder().
		WithImage("attachment://qr.png").
		WithFooter("발급 시각: 2026-09-04 15:20:53 (KST)")

	comps := builder.Build()
	if len(comps) == 0 {
		t.Fatal("expected non-empty components")
	}

	// First component should be MediaGallery (Top-Level)
	if _, ok := comps[0].(discordgo.MediaGallery); !ok {
		t.Fatalf("expected first component to be MediaGallery, got %T", comps[0])
	}

	// Verify top-level MediaGallery item URL
	mg := comps[0].(discordgo.MediaGallery)
	if len(mg.Items) != 1 || mg.Items[0].Media.URL != "attachment://qr.png" {
		t.Fatalf("unexpected media gallery item: %+v", mg)
	}

	// Verify footer exists and contains the issue time
	hasFooter := false
	for _, comp := range comps {
		if td, ok := comp.(discordgo.TextDisplay); ok {
			if strings.Contains(td.Content, "발급 시각") {
				hasFooter = true
			}
		}
	}
	if !hasFooter {
		t.Fatal("expected footer TextDisplay component in V2 components")
	}
}
